# Structuring Detection Rules
# Identifies transactions designed to avoid reporting requirements

name: "structuring_detection"
description: "Detects potential structuring patterns in transaction amounts"
enabled: true
severity: "critical"
score: 0.8
logic: "OR"

conditions:
  # Amounts just below $10,000 CTR threshold
  - field: "amount"
    operator: "near_threshold"
    value: 10000
    description: "Amount near $10,000 CTR threshold"
  
  # Multiple transactions just below $5,000
  - field: "amount"
    operator: "between"
    value: [4500, 4999]
    description: "Amount between $4,500-$4,999"
  
  # Common structuring amounts
  - field: "amount"
    operator: "in"
    value: [2999, 4999, 7999, 8999, 9000, 9500, 9800, 9900, 9950]
    description: "Common structuring amounts"
  
  # Suspiciously round amounts near thresholds
  - conditions:
      - field: "amount"
        operator: "greater_than"
        value: 8000
      - field: "amount"
        operator: "less_than" 
        value: 10000
      - field: "amount"
        operator: "regex"
        value: "\\d+00\\.00$"
    logic: "AND"
    description: "Round amounts between $8,000-$10,000"

# Additional metadata
tags: ["structuring", "ctr", "reporting", "avoidance"]
regulatory_basis: "31 CFR 1020.315 - Currency Transaction Reports"
alert_template: "Potential structuring detected: Transaction amount ${amount} may be designed to avoid reporting requirements"

# Scoring factors
score_factors:
  - name: "proximity_to_threshold"
    weight: 0.4
    description: "How close the amount is to reporting thresholds"
  
  - name: "amount_pattern"
    weight: 0.3
    description: "Whether amount follows common structuring patterns"
  
  - name: "frequency"
    weight: 0.3
    description: "Frequency of similar amounts from same customer"

# Investigation guidance
investigation_steps:
  - "Review customer's transaction history for similar amounts"
  - "Check for multiple transactions on same day or consecutive days"
  - "Verify business justification for specific amounts"
  - "Review customer's stated income and business activities"
  - "Check for related accounts or beneficial owners"

false_positive_indicators:
  - "Regular payroll or business operational amounts"
  - "Loan payments with specific contractual amounts"
  - "Insurance claims or settlements"
  - "Investment account transfers with documented source"
